logger implementation
Karthick9917/EmployeeManagementSystem pull request #6
Opened 2022-10-12 10:24 UTC by Karthick9917

2022-10-12 13:16 UTC, ponvel-i2i requested changes
Improve the logger information

2022-10-12 13:16 UTC, ponvel-i2i commented on com/ideas2it/employeeManagementSystem/dao/EmployeeDao.java
>          } catch (SQLException sqlException) {
This log should not be used for further debug. Add actual exception

2022-10-12 13:16 UTC, ponvel-i2i commented on com/ideas2it/employeeManagementSystem/main/EmployeeManagementSystem.java
>      public static void main(String[] args) {
same here

2022-10-12 13:16 UTC, ponvel-i2i commented on com/ideas2it/employeeManagementSystem/util/ConnectionUtil.java
> +package com.ideas2it.employeeManagementSystem.util;
Why this class show as a new file?

2022-10-12 13:16 UTC, ponvel-i2i commented on com/ideas2it/employeeManagementSystem/util/ValidationUtil.java
> +package com.ideas2it.employeeManagementSystem.util;
Why this also?

2022-10-13 12:02 UTC, aruni2isankar approved these changes

2022-10-13 16:57 UTC, merged