Project many-to-many hibernate implementation.
Karthick9917/EmployeeManagementSystem pull request #8
Opened 2022-10-31 14:29 UTC by Karthick9917

2022-11-01 07:06 UTC, ponvel-i2i requested changes

2022-11-01 07:06 UTC, ponnuvelgandhi commented on com/ideas2it/employeeManagementSystem/controller/EmployeeController.java
> +        return employeeService.getProjectById(projectId);
Use Project Service to get the project by project Id

2022-11-01 07:06 UTC, ponnuvelgandhi commented on com/ideas2it/employeeManagementSystem/controller/ProjectController.java
> +     * Passing the string and its return the true or false
Write proper comments

2022-11-01 07:06 UTC, ponnuvelgandhi commented on com/ideas2it/employeeManagementSystem/controller/ProjectController.java
> +        return projectService.getEmployeeById(employeeId);
Use employee service here

2022-11-01 07:06 UTC, ponnuvelgandhi commented on com/ideas2it/employeeManagementSystem/dao/impl/EmployeeDao.java
> +            throw new EmsException(Constants.NOT_ADDED_MESSAGE);
Use proper constants

2022-11-01 07:06 UTC, ponnuvelgandhi commented on com/ideas2it/employeeManagementSystem/dao/impl/ProjectDAO.java
> +            session.getTransaction().commit();
While getting the record, no need to commit the transaction

2022-11-01 07:06 UTC, ponvel-i2i commented on logs/app.log
> +2022-10-28 16:57:40 INFO o.h.Version:46 HHH000412: Hibernate Core {5.3.1.Final}
Should not commit log file

2022-11-04 08:16 UTC, Karthick9917 commented on com/ideas2it/employeeManagementSystem/controller/EmployeeController.java
> +        return employeeService.getProjectById(projectId);
Correction resolved

2022-11-04 08:17 UTC, Karthick9917 commented on com/ideas2it/employeeManagementSystem/controller/ProjectController.java
> +        return projectService.getEmployeeById(employeeId);
Correction resolved

2022-11-04 08:17 UTC, Karthick9917 commented on com/ideas2it/employeeManagementSystem/controller/ProjectController.java
> +     * Passing the string and its return the true or false
Correction resolved

2022-11-04 08:17 UTC, Karthick9917 commented on com/ideas2it/employeeManagementSystem/dao/impl/ProjectDAO.java
> +            session.getTransaction().commit();
Correction resolved

2022-11-04 08:17 UTC, Karthick9917 commented on com/ideas2it/employeeManagementSystem/dao/impl/EmployeeDao.java
> +            throw new EmsException(Constants.NOT_ADDED_MESSAGE);
Correction resolved

2022-11-04 08:18 UTC, Karthick9917 commented on logs/app.log
> +2022-10-28 16:57:40 INFO o.h.Version:46 HHH000412: Hibernate Core {5.3.1.Final}
Correction resolved

2022-11-07 16:00 UTC, aruni2isankar approved these changes

2022-11-08 04:28 UTC, merged